---
# Source: concourse/charts/postgresql/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-postgresql
  labels:
    app: postgresql
    chart: postgresql-0.13.1
    release: release-name
    heritage: Tiller
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"