---
# Source: concourse/templates/web-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-web
  labels:
    app: release-name-web
    chart: concourse-6.2.1
    heritage: Tiller
    release: release-name
