---
# Source: concourse/templates/web-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: release-name-web
  labels:
    app: release-name-web
    chart: concourse-6.2.1
    heritage: Tiller
    release: release-name
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]