---
# Source: concourse/templates/worker-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-worker
  labels:
    app: release-name-worker
    chart: concourse-6.2.1
    heritage: Tiller
    release: release-name
