---
# Source: concourse/templates/worker-role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: release-name-worker
  labels:
    app: release-name-worker
    chart: concourse-6.2.1
    heritage: Tiller
    release: release-name
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
