---
# Source: concourse/templates/worker-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: release-name-worker
  labels:
    app: release-name-worker
    chart: concourse-6.2.1
    heritage: Tiller
    release: release-name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-worker
subjects:
- kind: ServiceAccount
  name: release-name-worker
