---
# Source: concourse/templates/worker-policy.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: release-name-worker
  labels:
    app: release-name-worker
    chart: "concourse-6.2.1"
    release: "release-name"
    heritage: "Tiller"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: release-name-worker
